### ISSUE TITLE
React Pwa issue

### ISSUE THREAD

**Issue by Ashish117** [JamesBrill/react-speech-recognition#104]
Hi, I built a react PWA and implemented the library, I am using an iOS device with latest os, I am successfully able to use it in safari but as an app it is not asking for microphone permission when triggering ```SpeechRecognition.startListening()``` . I tested ```       navigator.mediaDevices.getUserMedia({
      audio: true
     });``` and it is asking for permission and starts recording but the library is not working on Pwa when it is added to homescreen.
     
     version: 3.8.2

**Comment by JamesBrill** [comment]
Hi @Ashish117 Some comments:
* It appears that Safari does not currently support Speech Recognition on PWAs. See the comment [here](https://firt.dev/ios-14.5/#speech-recognition-api): "_Unfortunately, the Speech Recognition API does NOT work inside a standalone PWA. The API is available, so a feature detection algorithm detects it, but nothing happens. My guess is that it has to do with the speech or microphone permission that is not working while in a PWA. Also, it has to do with Apple folks not testing within standalone apps, as usual._"
* Note that only the latest version of Safari on iOS supports the Speech Recognition API. It sounds like you're up-to-date - just make sure you're on Safari 14.5 or higher
* `react-speech-recognition` does not use the Media Devices API - instead it uses the [Speech Recognition API](https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition). Safari only just started supporting Speech Recognition, so this might explain the discrepancy if you have an older version. Note that `react-speech-recognition` _will_ use Media Devices if using a [polyfill](https://github.com/JamesBrill/react-speech-recognition/blob/master/docs/POLYFILLS.md)
* Speech Recognition requires an Internet connection, so will not function when your PWA users are offline

**Comment by JamesBrill** [comment]
Closed due to inactivity.
