### ISSUE TITLE
Safari 14.1.1(MacOS), Safari 14.6(IPhone), microphone not will stop listening when the user stops speaking

### ISSUE THREAD

**Issue by DmitryRback** [JamesBrill/react-speech-recognition#105]
If language: ua  microphone not will stop listening when the user stops speaking.

```
import React from 'react'
import SpeechRecognition, { useSpeechRecognition } from 'react-speech-recognition'

const Dictaphone = () => {
    const commands = [
        {
            command: 'Hello World',
            callback: (food) => alert('Hello World')
        },
        {
            command: 'Привет мир',
            callback: (food) => alert('Привет мир')
        },
        {
            command: 'Привіт світ',
            callback: (food) => alert('Привіт світ')
        },
    ]

    const { transcript, listening } = useSpeechRecognition({ commands })

    return (
        <div>
            <p>Microphone: {listening ? 'on' : 'off'}</p>
            <button onClick={() => SpeechRecognition.startListening({ continuous: false, language: 'uk-UA' })}>Start</button>
            <button onClick={SpeechRecognition.stopListening}>Stop</button>
            <p>{transcript}</p>
        </div>
    )
}
export default Dictaphone
```

**Comment by 0xf10yd** [comment]
You should either implement  `browserSupportsContinuousListening` state from the `useSpeechRecognition` 
```
if (browserSupportsContinuousListening) {
  SpeechRecognition.startListening({ continuous: true })
} else {
  // Fallback behaviour
}
```
to detect the browser support for continuous listening, ad that's because not all browsers have good support for it, or you can try the polyfills to enable/disable continuous listening on those browsers.

Also consider rechecking the documentation provided on the repo

**Comment by DmitryRback** [comment]
A real project has 
```
browserSupportsContinuousListening
```
, this is just an example. 
And I don’t need continuous listening. Now the microphone will not stop listening when the user stops talking.

**Comment by JamesBrill** [comment]
Hi @DmitryRback I did some testing and unfortunately, this appears to be a bug in Safari. For some languages, including at least Ukrainian and French, Apple's speech recognition API (I think it's Siri) is not able to detect the end of an utterance (a concept called [endpointing](https://developers.deepgram.com/guides/streaming/endpointing)). It appears that Apple's endpoint detection algorithm fails on these languages, which is a real shame - others like English and Chinese seem to work fine. I tested this with "vanilla" Speech Recognition code (i.e. no React) and the behaviour is the same. Apple's Speech Recognition implementation never emits any final results for these languages, only interim ones.

I don't actually know the best place to report such bugs to Apple, but [this](https://feedbackassistant.apple.com/) is apparently the place to go.

At this point, I would normally recommend you use a polyfill with `react-speech-recognition`, but neither of the APIs with polyfills currently support Ukrainian, I'm very sorry to say.

You have a few options, none of them great:
* Disable your voice input on Safari, at least for the unsupported languages
* Manually stop the microphone if enough time has passed without an interim result. For example, every time you get a new transcript, you could reset a 5 second timer. If the timer ever reaches 0, you can turn off the microphone via a callback that calls `SpeechRecognition.stopListening`

**Comment by JamesBrill** [comment]
Closed due to inactivity.
