### ISSUE TITLE
Audio file

### ISSUE THREAD

**Issue by nvd9411** [JamesBrill/react-speech-recognition#108]
Hello, I would like to ask that how could I get the audio file that is used for conversion from speech to text. I need that to put in the <audio> tag. 
Thank you so much.

**Comment by JamesBrill** [comment]
Hi @vdn19 I'd just like to clarify your use case:
* Would you like to take an input audio file (e.g. uploaded by the user) and run speech-to-text on it to convert it into text?
* Or would you like to generate an audio file while performing speech-to-text that the user can download?

Either way, this is not supported by the Speech Recognition API (to the best of my knowledge). This API sends audio streams to a third party service in the cloud and receives streams of text in response. I do not believe the stream is accessible to us.

However, there is a different API that could enable your use case, which is the [Web Audio API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API). Perhaps you can stream audio to your own Speech Recognition service (e.g. AWS Transcribe, Azure Cognitive Services, Speechly, etc) while also collecting the audio in a buffer to be converted into a file.

This is beyond the scope of `react-speech-recognition`, so you will need to write a custom solution. It sounds like an interesting use case though, so perhaps it's something you could make an open source library for.

Best of luck!

**Comment by JamesBrill** [comment]
Closed due to inactivity.
