### ISSUE TITLE
Voice recognition does not work when polyfill is applied in React

### ISSUE THREAD

**Issue by daehyunkim73** [JamesBrill/react-speech-recognition#115]
I am developing speech recognition in React.
However, when applying the following polyfill, voice recognition is not available.
The problem code followed the guidelines.

const appId = 'app id number';
const SpeechlySpeechRecognition = createSpeechlySpeechRecognition(appId);
SpeechRecognition.applyPolyfill(SpeechlySpeechRecognition);

English voice is recognized
but other languages ​​don't work
Is there anything we missed?
Is there anything I need to configure about polyfills in React?
Here's the full code...

:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: Issue Code  :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
import { createSpeechlySpeechRecognition } from '@speechly/speech-recognition-polyfill';
import SpeechRecognition, { useSpeechRecognition } from 'react-speech-recognition';

const appId = API_KEY;
const SpeechlySpeechRecognition = createSpeechlySpeechRecognition(appId);
SpeechRecognition.applyPolyfill(SpeechlySpeechRecognition);

1) const startListening = () => SpeechRecognition.startListening({ continuous: continuousGbn, language: 'en'  });
2) const startListening = () => SpeechRecognition.startListening({ continuous: continuousGbn, language: 'ko'  });
3) const startListening = () => SpeechRecognition.startListening({ continuous: continuousGbn, language: 'de'  });
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

**Comment by JamesBrill** [comment]
Hi @daehyunkim73 Last time I checked, Speechly does not currently support languages other than English, at least not in the API used in their polyfill (see polyfill [caveats](https://github.com/JamesBrill/react-speech-recognition/blob/master/docs/POLYFILLS.md#limitations)). They are looking into adding more languages though. From my experience, they are responsive to feedback - perhaps you can check in on the progress of multi-language support [here](https://www.speechly.com/contact/). I'll also drop them a message. 🙂

**Comment by JamesBrill** [comment]
Closed due to inactivity.
