### ISSUE TITLE
Listening timeout

### ISSUE THREAD

**Issue by yuvalkry** [JamesBrill/react-speech-recognition#119]
Hello,

  First, thank you for this very useful package!

  When there is no speech, it appears the 'listening' hook is turned off automatically.
  Is that intentional? I think it is a good idea. Is it possible to configure the time out?

  Thanks,
        Yuval

**Comment by JamesBrill** [comment]
Hi Yuval! If you are referring to the fact that the microphone will stop listening after you stop speaking, this is the default behaviour and is expected. It is the algorithm in the speech recognition engine that determines when the listening finishes. It will keep listening until it is confident the user has finished speaking - there is no specific timeout.

If you want the microphone to keep listening until you explicitly tell it to stop, you can turn on the `continuous` option. This is documented [here](https://github.com/JamesBrill/react-speech-recognition#continuous-listening).

Does that help?

**Comment by samuelkarani** [comment]
It would be nice to have a timeout - the current timeout is too short
