### ISSUE TITLE
stop is not working using polyfill for azure speech services

### ISSUE THREAD

**Issue by pfloresl** [JamesBrill/react-speech-recognition#120]
when stop is called, the red icon on chrome tab stays on.
  "microsoft-cognitiveservices-speech-sdk": "^1.17.0",
"web-speech-cognitive-services": "^7.1.1

my sequence to stop

 SpeechRecognition.stopListening();
    
abortlListening does remove red icon.

thank you

Also confuse on doc mentioning that it is async. await seems not be supported.

**Comment by JamesBrill** [comment]
Hi @pfloresl thanks for raising the issue. `stopListening` only became async in [version 3.3.0](https://github.com/JamesBrill/react-speech-recognition/releases/tag/v3.3.0) - try updating your installed version to get that functionality.

I'll play with the Azure polyfill and see if I also have difficulties stopping the microphone. Which browser are you using?

**Comment by JamesBrill** [comment]
@pfloresl This appears to be a bug in the Azure polyfill. I have raised an [issue](https://github.com/compulim/web-speech-cognitive-services/issues/166) with the author. In the meantime, `abortListening` should get you the behaviour you desire.
