### ISSUE TITLE
Code works on Chrome desktop but not on Edge

### ISSUE THREAD

**Issue by yuvalkry** [JamesBrill/react-speech-recognition#121]
Hello,

 The react app which uses react-speech-recognition works well with Chrome but no transcription when using Edge (v. 94) .
 The flag browserSupportsSpeechRecognition() is true but there is no transcription and the recognizer stops listening quickly.

 This demo, https://codepen.io/Rumyra/pen/bCphe, works well so the browser does support speech recognition, but it doesn't
 work somehow with the library.

   Thanks,
           Yuval

**Comment by yuvalkry** [comment]
Opened by mistake, sorry.

**Comment by yuvalkry** [comment]
James, eventually it worked on Edge just as well.

Before, I tried with Hebrew - which is supported on Chrome but not on Edge (apparently).
With English, it works well on Edge.

 Thanks again and good luck!
        Yuval

**Comment by Premrajcse** [comment]
Hi Yuval, react speech recognition not works in Edge browser but it works in chrome. Mic is enabling and listening in edge but transcription not happening. Could we have any solution?
