### ISSUE TITLE
How can I disable autoclose?

### ISSUE THREAD

**Issue by fsuaterdogan** [JamesBrill/react-speech-recognition#122]
Hi, thanks for the lib. My question is,

Its automaticly closing when I stop talking. How can I disable this? I want to just close on button clicks. Thanks

**Comment by JamesBrill** [comment]
Hi @fsuaterdogan 

@lnfernandobr is correct - you just need to pass the `continuous: true` option to `startListening` and the microphone will remain on until you explicitly call `stopListening` or `abortListening`.
