### ISSUE TITLE
Finding out whether a certain language is supported

### ISSUE THREAD

**Issue by yuvalkry** [JamesBrill/react-speech-recognition#123]
Hello James,

  Would it be possible to add a feature for finding whether a certain language is supported?
  (I don't know whether the browsers provide access to this query)

    Thanks,
          Yuval

**Comment by JamesBrill** [comment]
Hi Yuval,

I really wish browsers did expose that information! The supported list depends on the cloud API (usually owned by the browser vendor), which is external to the browser. If that information was available, I would create a unified list of languages in `react-speech-recognition` that warned the consumer in some way if a particular browser did not support a particular language.

You can guess the supported languages from these places:
* [For Chrome](https://cloud.google.com/speech-to-text/docs/languages)
* [For Safari](https://stackoverflow.com/a/50132407)

This is where using a polyfill is useful as it gives you a guarantee on language support across browsers.

If you choose to use the native speech recognition implementations, you'll need to manually test each language you want to support on each browser. Although they aren't completely standardised, the language code format does seem fairly consistent, which should make your life a little easier.

**Comment by yuvalkry** [comment]
I understand, thanks James.
