### ISSUE TITLE
Speechly addition languages?

### ISSUE THREAD

**Issue by peterzanetti** [JamesBrill/react-speech-recognition#134]
The README specifies additional language support coming to speechly polyfill. Is there a time frame on this? The apps I create on speechly side don't seem to support anything but English.

**Comment by daveydee33** [comment]
Hi @peterzanetti , I was interested in other languages and looking further into this as well.  Speechly currently only supports English and Finnish (the company is from Finland).  They currently have Spanish on their roadmap, but their main focus is on English.  I am interested in other languages as well, in case another polyfill becomes available :)

**Comment by JamesBrill** [comment]
Hi @peterzanetti @daveydee33 thanks for raising this! I understand your pain and have checked in again with Speechly to get a better idea of which languages they'll be supporting next and roughly when. Until then, we have two options to explore:
1. The [Microsoft Azure polyfill](https://github.com/JamesBrill/react-speech-recognition/blob/master/docs/POLYFILLS.md#microsoft-azure-cognitive-services)
2. This [in-progress AWS Transcribe polyfill](https://github.com/ceuk/speech-recognition-aws-polyfill). I can't quite recommend it for use yet as there's a couple of bugs that affect its usability. I've checked in with the author (who is aware of the bugs) and offered to help finish it. Once those bugs are ironed out, I'll start recommending it for integration with this library

**Comment by peterzanetti** [comment]
Ok. I would be much more inclined to use AWS Transcribe if the polyfill were complete, as I'm already using AWS Translate in this same feature. What sort of bugs still exist?

**Comment by JamesBrill** [comment]
@peterzanetti [This comment and the overall thread outlines the bugs](https://github.com/JamesBrill/react-speech-recognition/discussions/79#discussioncomment-831176) I found last time I tested the AWS polyfill. ceuk says he's back working on it again, though I'm sure he'd appreciate any contributions/support.

You and @daveydee33 may be interested to know that Speechly are not planning any new languages until end of 2022/start of 2023. When they do, the first planned languages will most likely be Spanish, German and French.

**Comment by peterzanetti** [comment]
Thanks @JamesBrill. I will wait until that polyfill is more mature before going much further. Right now I am looking at possibly using speechly in my app only when english is the set language (which would still be 80-90% of usage), and then the native processor for any other language.

**Comment by JamesBrill** [comment]
Keep an eye out for new supported languages in Speechly here https://www.speechly.com/blog
