### ISSUE TITLE
Question about continuous listening

### ISSUE THREAD

**Issue by Chengwei-Ouyang** [JamesBrill/react-speech-recognition#136]
I had set continuous property as true, but it doesn't recognize my speech after a few words, maybe two or three sentences. Could you give me some advices if I want to integrate it with a video call module?

**Comment by JamesBrill** [comment]
Hi @Chengwei-Ouyang could you share the code for the component you're using speech recognition in?

**Comment by Chengwei-Ouyang** [comment]
Thanks for your replay! I have solved the problem by using the Micorsoft cloud provider.
