### ISSUE TITLE
Uncaught ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by mutasim77** [JamesBrill/react-speech-recognition#176]
Hey there! 
I started working on a 'basic example' and encountered an error.
<img width="900" alt="Screen Shot 2023-06-03 at 4 45 47 PM" src="https://github.com/JamesBrill/react-speech-recognition/assets/96326525/701a57b1-8e08-4362-973c-9e2988322ef0">

I'm using a ```React``` app and have already installed the ```regenerator-runtime``` package by running the command ```npm i --save regenerator-runtime```. However, I'm still encountering an error. Has anyone else encountered this issue or know how to resolve it? Any assistance would be greatly appreciated.

**Comment by zetorama** [comment]
Have you imported the package somewhere? You could find your entry point (usually `index.js`) and just add this line:
```
import 'regenerator-runtime/runtime'
```

Also make sure to check out [Troubleshooting](https://github.com/JamesBrill/react-speech-recognition#regeneratorruntime-is-not-defined) section in README.md as this question was covered there.

**Comment by sebastienbarre** [comment]
Regenerator seems [pretty huge](https://bundlephobia.com/package/regenerator@0.14.10) as a dependency. Is there any way to avoid it? @JamesBrill ? Thanks
