### ISSUE TITLE
Randomly doesnt work on iOS devices

### ISSUE THREAD

**Issue by Facuiguacel** [JamesBrill/react-speech-recognition#216]
So I'm developing a Nextjs app that uses this library and while testing it on my device (iPhone 8 Plus, iOS 16.7.10) it works everytime, yet when I ask others to test it (iPhones 14/15) it works ~10% of the time, speech recognition gets stuck on listening or fails. I understand it's a bit vague but maybe someone has the answer.
Any idea what the issue might be?

**Comment by nafets33** [comment]
@Facuiguacel did you figure out a solution, i've been trying to figure out how to get it to work on Mobile devices.
