### ISSUE TITLE
Mobile issues

### ISSUE THREAD

**Issue by bruno-candia** [JamesBrill/react-speech-recognition#22]
Hello,

I'm developing a project using speech recognition, and the project is already online using the AWS server. However, I have a problem when accessing the page on mobile, because I want to use speech recognition with continuous in true, but I read in the documentation that this is not possible due to a bug, so I would like to know if you have any method to use continuos in true and not turn off the microphone all the time.

**Comment by farhanbombay** [comment]
That is the limitation of android or maybe security purposes. I am facing the same problem

**Comment by JamesBrill** [comment]
I have attempted to work around this Android Chrome bug in version `2.0.6`. No guarantees that it will work on all Android devices/browsers, but you should be able to use Speech Recognition with the config you want now.
