### ISSUE TITLE
postinstall error on installation with new 2.0.6 version

### ISSUE THREAD

**Issue by NikkiMeganMoore** [JamesBrill/react-speech-recognition#32]
The postinstall script is throwing an error, there is no "example" folder to cd into

<img width="771" alt="Screen Shot 2020-06-25 at 12 44 51 PM" src="https://user-images.githubusercontent.com/38014424/85780297-b17ede80-b6e1-11ea-90c7-cb73e31e1a98.png">

This was especially confusing since I also have a script to cd into my own example folder and install  :)

**Comment by JamesBrill** [comment]
Ah I see what's happening there. That command assumes the `example` folder from this repo is present, when in fact only the `src` is published. On it, will get back to you with a fixed version shortly.

**Comment by JamesBrill** [comment]
Okay @NikkiMeganMoore give it a shot with `2.0.7`

**Comment by NikkiMeganMoore** [comment]
@JamesBrill  Works! Thanks
