### ISSUE TITLE
Using onTranscriptionChanged(text) {} on react class component 

### ISSUE THREAD

**Issue by HaywoodSolutions** [JamesBrill/react-speech-recognition#45]
How do you mount SpeechRecognition onto a react class component. Ideally I would like a method for `onTranscriptionChanged: (text: string) => void` in my component

**Comment by JamesBrill** [comment]
Hi Thomas! Firstly, I would say that if you are using React 16.8 or above and can refactor your class component into a functional component, that would be the best solution and would make your React app cleaner overall. If you did that, you could use `react-speech-recognition` version 3 and utilise the `useSpeechRecognition` hook and `useEffect` to detect transcription changes.

If that's not an option, you will need to use version 2 (the latest version 2 was `2.1.4` and is documented [here](https://github.com/JamesBrill/react-speech-recognition/tree/v2.1.4)). This offers a [higher-order component](https://reactjs.org/docs/higher-order-components.html) that injects the transcript into your component. To pick up transcript changes in your class component with this older version, you can add a lifecycle hook to your component like this:
```
componentWillReceiveProps(nextProps) {
  if (this.props.transcript !== nextProps.transcript) {
    onTranscriptionChanged(nextProps.transcript)
  }
}
```

If you want the features available in version 3 (e.g. commands) but still need to use a class component, I believe there are hacky ways to get React hooks to work with class components (e.g. [this article](https://infinum.com/the-capsized-eight/how-to-use-react-hooks-in-class-components)), but I wouldn't recommend it as they are two different paradigms for writing React components.

**Comment by HaywoodSolutions** [comment]
Perfect thanks, got it sorted!
