### ISSUE TITLE
Having issue that `ReferenceError: regeneratorRuntime is not defined` showing for nextjs project

### ISSUE THREAD

**Issue by singh-anita** [JamesBrill/react-speech-recognition#48]
Server Error
ReferenceError: regeneratorRuntime is not defined for example:  at /node_modules/react-speech-recognition/lib/RecognitionManager.js:168:61

**Comment by JamesBrill** [comment]
Hi @singh-anita ! The regenerator runtime is needed to run the compiled `async/await` code in this library. I believe there are a couple of options to add this:
- Install `regenerator-runtime` into your app and then import it with `import 'regenerator-runtime/runtime'`
- Use the Babel transform runtime plugin and combine with `@babel/runtime` (see https://babeljs.io/docs/en/babel-plugin-transform-runtime)
