### ISSUE TITLE
regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by amirHossein-Ebrahimi** [JamesBrill/react-speech-recognition#55]
Install `react-speech-recognition` and use React `@latest v16.13.1`

https://stackblitz.com/edit/react-odefag

**Comment by JamesBrill** [comment]
Hi @amirHossein-Ebrahimi See https://github.com/JamesBrill/react-speech-recognition/issues/48#issuecomment-666801823

**Comment by amirHossein-Ebrahimi** [comment]
Thank you 🙏
