### ISSUE TITLE
Continuous mode doesn't clear transcript

### ISSUE THREAD

**Issue by thiagoss** [JamesBrill/react-speech-recognition#58]
Not sure if this is a problem with this project or the underlying Web API. When using continuous mode it keeps listening as expected, but the transcript text is never cleared, even after issuing stopListening().

I also tried calling resetTranscript() after calling stopListening() but that seems to turn on listening again for some reason.

**Comment by JamesBrill** [comment]
Hi @thiagoss Can you please share the following:
- The device and browser you see this issue on
- The version of `react-speech-recognition` that you're using
- A code snippet of your usage of `react-speech-recognition`

Some initial comments:
- With continuous listening, only `resetTranscript` will clear the transcript. `stopListening` will just turn off the microphone, which prevents any additional transcript from being added; the existing transcript will remain.
- `I also tried calling resetTranscript() after calling stopListening() but that seems to turn on listening again for some reason.` This is surprising and is not something I have seen before. As mentioned above, a code snippet will help me understand your configuration and the behaviour you are seeing.
- What is the exact behaviour you would like to achieve? Perhaps you could describe your use case.

**Comment by thiagoss** [comment]
I just got latest master as of today (v3.2.0) and turned the example into the issue by adding my code to it:
https://github.com/thiagoss/react-speech-recognition/tree/example-issue-58

It makes sense that stopListening doesn't clear the transcript but I'm still unsure why resetTranscript seems to make it start listening again. I was hoping resetting the transcript wouldn't change current listening state.

**Comment by thiagoss** [comment]
It worked! Thanks for the quick fix!
