### ISSUE TITLE
Mobile Support? 

### ISSUE THREAD

**Issue by floan** [JamesBrill/react-speech-recognition#69]
Everything is working perfectly on my laptop, however, nothing seems to happen when I try to run the app on mobile (React App on a mobile browser). Is there mobile support / does the API automatically request microphone access like it does for desktop?  

I see a similar problem popped up in Issue #22 , is version 3 any more successful in getting it to work on android browsers?

**Comment by JamesBrill** [comment]
Hi @floan ! From my experience, the support for the Web Speech API is limited on mobile. It is completely unavailable on iOS and limited to Chrome/Samsung Internet on Android. Regarding speech recognition, we are limited by what the native OS allows the browser to perform and for this API, many devices will automatically deny the browser access to the microphone.

On my Android device, Chrome asks me for permission to use my microphone when testing the [Mozilla demo](https://mdn.github.io/web-speech-api/speech-color-changer/). Once granted, that demo works for me.

A few questions:
* What device and browser are you using?
* Does the above demo work for you?
* What is the value of `browserSupportsSpeechRecognition` on your web app on your mobile device? It should be `false` if the browser does not support speech recognition, in which case you'll need to render some fallback content instead.

**Comment by floan** [comment]
Hello! 

Sorry for the late response. You're right, my device/browser doesn't support the Web Speech API. Thanks for the info!
