### ISSUE TITLE
Multiple commands using the same callback

### ISSUE THREAD

**Issue by Nitzahon** [JamesBrill/react-speech-recognition#70]
What is the best way to do this, do I have to define multiple commands with the same callback, or can a command be an array of possible strings which will call the same callback?

**Comment by Nitzahon** [comment]
Also what is the best way to pass the entire command as a callback argument?

**Comment by Nitzahon** [comment]
so it seems you can put an array of commands to use the same callback

**Comment by JamesBrill** [comment]
Array commands are not actually supported (though they probably should be). See [this comment](https://github.com/JamesBrill/react-speech-recognition/issues/71#issuecomment-731625889) on your other issue.

**Comment by JamesBrill** [comment]
Reopening to remind myself to add support for array commands.

**Comment by JamesBrill** [comment]
@Nitzahon Array-based commands are now supported in [v3.4.0](https://github.com/JamesBrill/react-speech-recognition/releases/tag/v3.4.0)

**Comment by Nitzahon** [comment]
You sir, are what is known as a [mensch](https://en.wikipedia.org/wiki/Mensch)

**Comment by Nitzahon** [comment]
On question though, how do you send  the spoken command itself from the array as the callbacks argument? like this:
```
    {
      command: ['Hello', 'Hi'],
      callback: () => setMessage(command),
      matchInterim: true
    }
```
or like this:
```
    {
      command: ['Hello', 'Hi'],
      callback: () => setMessage(command, spokenPhrase),
      matchInterim: true
    }
```
or something else?  will I still need to use the same solution you gave me in 3.3.0?

```

  const videoCommandCallback = (command, spokenPhrase) => {
    sendAns(command)
    handleReset()

  }
  const videoCommands = ['Hello', 'Hi'].map(phrase => ({
    command: phrase,
    callback: videoCommandCallback,
    isFuzzyMatch: true,
    fuzzyMatchingThreshold: 0.6
  }))

```

**Comment by Nitzahon** [comment]
so this works:
```
  const videoCommandCallback = (command, spokenPhrase) => {
    sendAns(command)
    handleReset()

  }
const commands =[
    {
      command: ['Hello', 'Hi'],
      callback: videoCommandCallback,
      isFuzzyMatch: true,
      fuzzyMatchingThreshold: 0.6,
    }
]
```

There is only the issue, of, if multiple commands match the fuzzy requirements, all are called with the callback instead of the command which most closely matches.
i.e.:  If my array contains the commands `["Everything is working", "Nothing is working"]`, my fuzzyMatchingThreshold is set to 0.7 or lower and I say "Everything is working"  The callback will be called twice, once for "Everything is working", and once for "Nothing is working", even though "Everything is working" more closely matches.

**Comment by JamesBrill** [comment]
Ah yes, it would make sense to know which of the commands in the array was matched. I'll make a quick update.

**Comment by JamesBrill** [comment]
@Nitzahon Give [v3.5.0](https://github.com/JamesBrill/react-speech-recognition/releases/tag/v3.5.0) a try. The callback can get the matched command from the last argument, which will be an object with a new property: `command`.

**Comment by JamesBrill** [comment]
>There is only the issue, of, if multiple commands match the fuzzy requirements, all are called with the callback instead of the command which most closely matches.
i.e.: If my array contains the commands ["Everything is working", "Nothing is working"], my fuzzyMatchingThreshold is set to 0.7 or lower and I say "Everything is working" The callback will be called twice, once for "Everything is working", and once for "Nothing is working", even though "Everything is working" more closely matches.

This is an interesting point. It may be desirable in some cases to just trigger the callback on the _best_ match when fuzzy matching is used. If this would be a useful feature for you, let me know and I can look into it.

**Comment by Nitzahon** [comment]
> > There is only the issue, of, if multiple commands match the fuzzy requirements, all are called with the callback instead of the command which most closely matches.
> > i.e.: If my array contains the commands ["Everything is working", "Nothing is working"], my fuzzyMatchingThreshold is set to 0.7 or lower and I say "Everything is working" The callback will be called twice, once for "Everything is working", and once for "Nothing is working", even though "Everything is working" more closely matches.
> 
> This is an interesting point. It may be desirable in some cases to just trigger the callback on the _best_ match when fuzzy matching is used. If this would be a useful feature for you, let me know and I can look into it.

Letting you know, this would be useful ;-)

**Comment by Nitzahon** [comment]
> @Nitzahon Give [v3.5.0](https://github.com/JamesBrill/react-speech-recognition/releases/tag/v3.5.0) a try. The callback can get the matched command from the last argument, which will be an object with a new property: `command`.

tried this.  Did not work:
```
    {
      command: videoCommandPhrases.commands,
      callback: ({ command }) => console.log("command is: "+command),
      isFuzzyMatch: true,
      fuzzyMatchingThreshold: 0.6,
    }
```
expected outout: `"command is: Everything is Working"`
actual output:   `"command is: undefined"`

**Comment by JamesBrill** [comment]
I'll repro this and see what I can do.

**Comment by JamesBrill** [comment]
Initial tests indicate this issue is exclusive to fuzzy-matched commands. My bad for not testing that case when I made that release. Investigating.

**Comment by JamesBrill** [comment]
Ah wait, this does make sense. Fuzzy callbacks get three other arguments before that one.

**Comment by JamesBrill** [comment]
With fuzzy commands, you can use the first arg like before:
```
    {
      command: ["Everything is working", "Nothing is working"],
      callback: (command) => console.log("command is: "+command),
      isFuzzyMatch: true,
      fuzzyMatchingThreshold: 0.6,
    },
```

**Comment by JamesBrill** [comment]
This does make me want to clean up the API a bit. Ideally, there would just be one object arg for both fuzzy and non-fuzzy commands, and the callback could unpack whatever it needed.

Before I do that, I'm going to look into your request for "closest match wins" for fuzzy commands.

**Comment by JamesBrill** [comment]
@Nitzahon Give [v3.6.0](https://github.com/JamesBrill/react-speech-recognition/releases/tag/v3.6.0) a try - it adds an option to only trigger the callback once, on the best fuzzy match.
