### ISSUE TITLE
Does the speech recognition function work in Electron?

### ISSUE THREAD

**Issue by wann2** [JamesBrill/react-speech-recognition#85]
I wonder whether this speech recognition function works in Electron.

**Comment by JamesBrill** [comment]
Hi @wann2 I don't believe the Web Speech API is supported in Electron, though I haven't experimented with it before.

If it doesn't, you do have the option of combining the [latest release](https://github.com/JamesBrill/react-speech-recognition/releases/tag/v3.7.0) of `react-speech-recognition` with Azure Cognitive Services and [this polyfill](https://github.com/compulim/web-speech-cognitive-services) to enable that functionality in Electron. If you do, let me know how it goes - Electron is uncharted territory for this library.
