### ISSUE TITLE
Why example not working after i stop speaking ?

### ISSUE THREAD

**Issue by fungerouscode** [JamesBrill/react-speech-recognition#91]
I used ```continuous``` but it's not working ? Please help me

**Comment by JamesBrill** [comment]
Hi @fungerouscode Could you provide the code you're using? Are you exactly using the example code from this repository? Or one of the examples from the README?

Also, are you using Chrome on Android? We found recently that Chrome on Android does not support continuous listening (https://github.com/JamesBrill/react-speech-recognition/issues/89).
