### ISSUE TITLE
iOS devices

### ISSUE THREAD

**Issue by Alastair1234** [JamesBrill/react-speech-recognition#98]
https://firt.dev/ios-14.5/#speech-recognition-api

Following this repo with interest and had been reading about iOS 14.5.  Are iOS devices supported now?

**Comment by JamesBrill** [comment]
Hi @Alastair1234 In theory, yes! I've tested Safari 14.1 on Mac and the native Speech Recognition API there works great with `react-speech-recognition`. See [this discussion](https://github.com/JamesBrill/react-speech-recognition/discussions/94) for more context.

From my understanding, iOS 14.5 also uses Safari 14.1 so should also support it. I don't have an iOS device, so it would be awesome if you can confirm if it works on that platform too. I'm curious to know what the user experience for web speech recognition is like on iOS - on Android, it can be rather painful.

**Comment by Alastair1234** [comment]
Many thanks for the information.  I will try it and let you know.

**Comment by JamesBrill** [comment]
Closed due to inactivity.
